/**
 * 시중 수학 교재와 이 지도의 단원을 잇는 자료.
 *
 * 왜 필요한가
 *   교사는 "이 단원이 막혔다"까지 알아내도, 그다음에 "그럼 어느 교재 몇 단원을 펴야 하나"에서 다시 막힌다.
 *   여기서 단원 ID와 교재 목차를 이어 두면 그 한 걸음이 사라진다.
 *
 * 지키는 규칙
 * 1. **목차는 실제로 긁은 그대로 적는다.** 요약하거나 다듬지 않는다. 출처 URL을 반드시 남긴다.
 * 2. 단원 연결(`unitId`)은 제목이 맞아떨어질 때만 건다. 억지로 맞추지 않는다.
 *    맞는 단원이 없으면 `null`로 두고 "이 교재에만 있는 장"으로 보여 준다.
 * 3. 교재의 구성·특징은 **출판사가 스스로 밝힌 설명**만 쓴다. 커뮤니티 후기는 쓰지 않는다.
 *    (`docs/검수-기록.md`의 근거 기준을 그대로 따른다.)
 */
import type { GradeId, TermId, UnitId } from "./schema.ts";

export type BookLevel = "초등" | "중등" | "고등";

/** 교재가 학습 흐름에서 맡는 자리. 출판사 설명에서 읽어 낸 것만 적는다. */
export type BookRole = "개념" | "유형" | "심화" | "내신";

export type Book = {
  /** 짧은 식별자. 화면 주소에도 쓴다. 예: "ssen-mid" */
  id: string;
  /** 화면에 쓰는 이름. 예: "쎈 중등 수학" */
  name: string;
  publisher: string;
  level: BookLevel;
  role: BookRole;
  /** 출판사가 밝힌 구성. 인용에 가깝게 적는다. */
  structure: string;
  /** 출판사 소개에서 읽은 특징. 없으면 비워 둔다. */
  publisherNote?: string;
  /** 이 교재를 어떤 학생에게 권할 수 있는지. 출판사 설명 범위 안에서만 적는다. */
  fitFor?: string;
};

/** 교재 한 권(학기 단위)의 목차 한 줄. */
export type BookChapter = {
  /** 대단원 표기가 있으면 그대로. 예: "I. 소인수분해" */
  part?: string;
  /** 중단원(장) 제목. 긁은 그대로. */
  title: string;
  /** 이 장이 대응하는 우리 단원. 맞는 것이 없으면 null. */
  unitId: UnitId | null;
};

/** 교재 × 학년 × 학기 한 권. */
export type BookVolume = {
  bookId: string;
  grade: GradeId;
  term: TermId;
  /** 몇 년판인지. 예: "2026년판" */
  edition: string;
  /** 목차를 긁은 상품 페이지 */
  source: string;
  /** 긁은 날짜 */
  checked: string;
  chapters: BookChapter[];
};

export const BOOKS: Book[] = [
  {
    id: "ssen-mid",
    name: "쎈 중등 수학",
    publisher: "좋은책신사고",
    level: "중등",
    role: "유형",
    structure: "A·B·C 3단계 난이도, B단계는 하·중·상으로 세분",
    publisherNote: "전국 중학교 학교 시험 기출을 유형별로 총정리했다고 소개합니다. 권마다 150여 개 유형에 1100~1300문제 규모입니다.",
    fitFor: "개념은 섰는데 문제에서 막힐 때",
  },
  {
    id: "ssen-high",
    name: "쎈 고등 공통수학",
    publisher: "좋은책신사고",
    level: "고등",
    role: "유형",
    structure: "A·B·C 3단계 난이도",
    publisherNote: "학교 시험 출제 유형을 유형별로 정리한 문제 기본서로 소개합니다.",
    fitFor: "개념은 섰는데 문제에서 막힐 때",
  },
  {
    id: "rpm-mid",
    name: "개념원리 RPM 중학 수학",
    publisher: "개념원리",
    level: "중등",
    role: "유형",
    structure: "교과서 문제 → 유형 익히기 → 시험에 꼭 나오는 문제 → 서술형 → 실력UP",
    publisherNote: "유형별 문제 학습서로, 개념원리 본교재의 해당 개념 쪽수를 표시해 두었다고 소개합니다.",
    fitFor: "개념은 섰는데 문제에서 막힐 때",
  },
  {
    id: "rpm-high",
    name: "개념원리 RPM 고등 공통수학",
    publisher: "개념원리",
    level: "고등",
    role: "유형",
    structure: "유형별 문제 구성",
    publisherNote: "개념 학습 뒤 유형을 정리하는 문제 기본서로 소개합니다.",
    fitFor: "개념은 섰는데 문제에서 막힐 때",
  },
  {
    id: "gnw-mid",
    name: "개념원리 중학 수학",
    publisher: "개념원리",
    level: "중등",
    role: "개념",
    structure: "개념 설명과 예제 중심",
    publisherNote: "개념의 원리를 설명하는 기본서로 소개합니다.",
    fitFor: "개념이 흔들려 처음부터 다시 세워야 할 때",
  },
  {
    id: "gnw-high",
    name: "개념원리 공통수학",
    publisher: "개념원리",
    level: "고등",
    role: "개념",
    structure: "개념 설명과 예제 중심",
    publisherNote: "개념의 원리를 설명하는 기본서로 소개합니다.",
    fitFor: "개념이 흔들려 처음부터 다시 세워야 할 때",
  },
  {
    id: "didim-basic",
    name: "디딤돌 초등수학 기본편",
    publisher: "디딤돌교육",
    level: "초등",
    role: "개념",
    structure: "교과 개념과 기본 유형",
    publisherNote: "교과서 개념을 익히고 기본 문제로 다지는 구성으로 소개합니다.",
    fitFor: "개념이 흔들려 처음부터 다시 세워야 할 때",
  },
  {
    id: "choisangwi",
    name: "최상위 초등수학",
    publisher: "디딤돌교육",
    level: "초등",
    role: "심화",
    structure: "심화 유형과 최상위 문제",
    publisherNote: "상위권을 위한 심화 학습서로 소개합니다.",
    fitFor: "기본과 유형이 이미 서 있을 때. 진단에서 막힌 단원이 있다면 여기부터 펴지 마세요",
  },
  {
    id: "checkcheck",
    name: "체크체크 수학",
    publisher: "천재교육",
    level: "중등",
    role: "내신",
    structure: "개념 확인과 학교 시험 대비",
    publisherNote: "학교 시험 대비를 겨냥한 구성으로 소개합니다.",
    fitFor: "학교 시험을 앞두고 있을 때",
  },
  {
    id: "ilpum",
    name: "일품 중등 수학",
    publisher: "좋은책신사고",
    level: "중등",
    role: "심화",
    structure: "심화 유형 중심",
    publisherNote: "상위권을 위한 심화 문제서로 소개합니다.",
    fitFor: "기본과 유형이 이미 서 있을 때. 진단에서 막힌 단원이 있다면 여기부터 펴지 마세요",
  },
  {
    id: "baekbal",
    name: "100발 100중 개념수학",
    publisher: "에듀원",
    level: "중등",
    role: "개념",
    structure: "개념과 기본 문제",
    publisherNote: "개념을 짚고 기본 문제로 확인하는 구성으로 소개합니다.",
    fitFor: "개념이 흔들려 처음부터 다시 세워야 할 때",
  },
  {
    id: "mapl",
    name: "마플 교과서 공통수학",
    publisher: "희망에듀",
    level: "고등",
    role: "개념",
    structure: "교과서 개념과 예제 중심",
    publisherNote: "교과서 개념을 자세히 풀어 설명하는 구성으로 소개합니다.",
    fitFor: "개념이 흔들려 처음부터 다시 세워야 할 때",
  },
];

export const BOOK_VOLUMES: BookVolume[] = [
  {
    bookId: "ssen-mid",
    grade: "m1",
    term: "s1",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/161362446",
    checked: "2026-08-14",
    chapters: [
      { part: "I. 소인수분해", title: "01 소인수분해", unitId: "m1-s1-01" },
      { part: "I. 소인수분해", title: "02 최대공약수와 최소공배수", unitId: null },
      { part: "II. 정수와 유리수", title: "03 정수와 유리수", unitId: "m1-s1-02" },
      { part: "II. 정수와 유리수", title: "04 유리수의 계산", unitId: null },
      { part: "III. 방정식", title: "05 문자의 사용과 식", unitId: "m1-s1-03" },
      { part: "III. 방정식", title: "06 일차방정식의 풀이", unitId: "m1-s1-04" },
      { part: "III. 방정식", title: "07 일차방정식의 활용", unitId: null },
      { part: "IV. 그래프와 비례", title: "08 좌표평면과 그래프", unitId: "m1-s1-05" },
      { part: "IV. 그래프와 비례", title: "09 정비례와 반비례", unitId: null },
    ],
  },
  {
    bookId: "ssen-mid",
    grade: "m1",
    term: "s2",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/145575803",
    checked: "2026-08-14",
    chapters: [
      { part: "Ⅰ. 기본 도형", title: "01 기본 도형", unitId: "m1-s2-01" },
      { part: "Ⅰ. 기본 도형", title: "02 위치 관계", unitId: null },
      { part: "Ⅰ. 기본 도형", title: "03 평행선", unitId: null },
      { part: "Ⅰ. 기본 도형", title: "04 작도와 합동", unitId: "m1-s2-02" },
      { part: "Ⅱ. 평면도형", title: "05 다각형", unitId: "m1-s2-03" },
      { part: "Ⅱ. 평면도형", title: "06 원과 부채꼴", unitId: null },
      { part: "Ⅲ. 입체도형", title: "07 다면체", unitId: "m1-s2-04" },
      { part: "Ⅲ. 입체도형", title: "08 회전체", unitId: null },
      { part: "Ⅲ. 입체도형", title: "09 입체도형의 겉넓이와 부피", unitId: null },
      { part: "Ⅳ. 통계", title: "10 도수분포표", unitId: null },
      { part: "Ⅳ. 통계", title: "11 상대도수", unitId: null },
    ],
  },
  {
    bookId: "ssen-mid",
    grade: "m2",
    term: "s1",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/153914550",
    checked: "2026-08-14",
    chapters: [
      { part: "I. 수와 식", title: "01 유리수와 소수", unitId: null },
      { part: "I. 수와 식", title: "02 단항식의 계산", unitId: "m2-s1-02" },
      { part: "I. 수와 식", title: "03 다항식의 계산", unitId: null },
      { part: "II. 부등식", title: "04 일차부등식", unitId: "m2-s1-03" },
      { part: "II. 부등식", title: "05 일차부등식의 활용", unitId: null },
      { part: "III. 방정식", title: "06 연립일차방정식", unitId: "m2-s1-04" },
      { part: "III. 방정식", title: "07 연립일차방정식의 풀이", unitId: null },
      { part: "III. 방정식", title: "08 연립일차방정식의 활용", unitId: null },
      { part: "IV. 함수", title: "09 일차함수와 그래프 ⑴", unitId: "m2-s1-05" },
      { part: "IV. 함수", title: "10 일차함수와 그래프 ⑵", unitId: null },
      { part: "IV. 함수", title: "11 일차함수와 일차방정식의 관계", unitId: "m2-s1-06" },
    ],
  },
  {
    bookId: "ssen-mid",
    grade: "m2",
    term: "s2",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/172734767",
    checked: "2026-08-14",
    chapters: [
      { part: "Ⅰ. 삼각형의 성질", title: "01 삼각형의 성질 (1)", unitId: "m2-s2-01" },
      { part: "Ⅰ. 삼각형의 성질", title: "02 삼각형의 성질 (2)", unitId: null },
      { part: "Ⅱ. 사각형의 성질", title: "03 평행사변형", unitId: "m2-s2-02" },
      { part: "Ⅱ. 사각형의 성질", title: "04 여러 가지 사각형", unitId: null },
      { part: "Ⅲ. 입체도형", title: "05 도형의 닯음", unitId: null },
      { part: "Ⅲ. 입체도형", title: "06 평행선 사이의 선분의 길이의 비", unitId: null },
      { part: "Ⅲ. 입체도형", title: "07 삼각형의 무게중심", unitId: null },
      { part: "Ⅲ. 입체도형", title: "08 닮음의 활용", unitId: null },
      { part: "Ⅳ. 피타고라스 정리", title: "09 피타고라스 정리", unitId: "m2-s2-05" },
      { part: "Ⅴ. 확률", title: "10 경우의 수", unitId: "m2-s2-06" },
      { part: "Ⅴ. 확률", title: "11 확률", unitId: null },
    ],
  },
  {
    bookId: "ssen-mid",
    grade: "m3",
    term: "s1",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/122972159",
    checked: "2026-08-14",
    chapters: [
      { part: "I. 제곱근과 실수", title: "01 제곱근의 뜻과 성질 8", unitId: "m3-s1-01" },
      { part: "I. 제곱근과 실수", title: "02 무리수와 실수 28", unitId: null },
      { part: "I. 제곱근과 실수", title: "03 근호를 포함한 식의 곱셈과 나눗셈 38", unitId: null },
      { part: "I. 제곱근과 실수", title: "04 근호를 포함한 식의 덧셈과 뺄셈 52", unitId: null },
      { part: "II. 다항식의 곱셈과 인수분해", title: "05 다항식의 곱셈 68", unitId: "m3-s1-03" },
      { part: "II. 다항식의 곱셈과 인수분해", title: "06 다항식의 인수분해 88", unitId: null },
      { part: "II. 다항식의 곱셈과 인수분해", title: "07 인수분해 공식의 활용 106", unitId: null },
      { part: "III. 이차방정식", title: "08 이차방정식의 풀이 ⑴ 120", unitId: "m3-s1-04" },
      { part: "III. 이차방정식", title: "09 이차방정식의 풀이 ⑵ 132", unitId: null },
      { part: "III. 이차방정식", title: "10 이차방정식의 활용 142", unitId: null },
      { part: "IV. 이차함수", title: "11 이차함수의 그래프 ⑴ 160", unitId: "m3-s1-05" },
      { part: "IV. 이차함수", title: "12 이차함수의 그래프 ⑵ 178", unitId: null },
    ],
  },
  {
    bookId: "ssen-mid",
    grade: "m3",
    term: "s2",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/126414647",
    checked: "2026-08-14",
    chapters: [
      { part: "I. 삼각비", title: "01 삼각비", unitId: "m3-s2-01" },
      { part: "I. 삼각비", title: "02 삼각비의 활용", unitId: null },
      { part: "II. 원의 성질", title: "03 원과 직선", unitId: "m3-s2-02" },
      { part: "II. 원의 성질", title: "04 원주각", unitId: null },
      { part: "II. 원의 성질", title: "05 원주각의 활용", unitId: null },
      { part: "III. 통계", title: "06 대푯값과 산포도", unitId: "m3-s2-03" },
      { part: "III. 통계", title: "07 상관관계", unitId: null },
    ],
  },
  {
    bookId: "ssen-high",
    grade: "h1",
    term: "s1",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/143336245",
    checked: "2026-08-14",
    chapters: [
      { part: "Ⅰ. 다항식", title: "01 다항식의 연산 8", unitId: "h1-s1-01" },
      { part: "Ⅰ. 다항식", title: "02 나머지 정리와 인수분해 24", unitId: null },
      { part: "Ⅱ. 방정식", title: "03 복소수 46", unitId: "h1-s1-02" },
      { part: "Ⅱ. 방정식", title: "04 이차방정식 62", unitId: "h1-s1-03" },
      { part: "Ⅱ. 방정식", title: "05 이차방정식과 이차함수 82", unitId: null },
      { part: "Ⅱ. 방정식", title: "06 여러 가지 방정식 98", unitId: "h1-s1-04" },
      { part: "Ⅲ. 부등식", title: "07 일차부등식 116", unitId: null },
      { part: "Ⅲ. 부등식", title: "08 이차부등식 130", unitId: null },
      { part: "Ⅳ. 순열과 조합", title: "09 순열과 조합 150", unitId: null },
      { part: "Ⅴ. 행렬", title: "10 행렬과 그 연산 174", unitId: "h1-s1-06" },
    ],
  },
  {
    bookId: "ssen-high",
    grade: "h1",
    term: "s2",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/177284738",
    checked: "2026-08-14",
    chapters: [
      { part: "Ⅰ. 도형의 방정식", title: "01 평면좌표 8", unitId: "h1-s2-01" },
      { part: "Ⅰ. 도형의 방정식", title: "02 직선의 방정식 22", unitId: null },
      { part: "Ⅰ. 도형의 방정식", title: "03 원의 방정식 42", unitId: null },
      { part: "Ⅰ. 도형의 방정식", title: "04 도형의 이동 64", unitId: null },
      { part: "Ⅱ. 집합과 명제", title: "05 집합의 뜻과 표현 82", unitId: "h1-s2-02" },
      { part: "Ⅱ. 집합과 명제", title: "06 집합의 연산 98", unitId: null },
      { part: "Ⅱ. 집합과 명제", title: "07 명제 116", unitId: null },
      { part: "Ⅲ. 함수", title: "08 함수 142", unitId: null },
      { part: "Ⅲ. 함수", title: "09 유리식과 유리함수 166", unitId: null },
      { part: "Ⅲ. 함수", title: "10 무리식과 무리함수 184", unitId: null },
    ],
  },
  {
    bookId: "rpm-mid",
    grade: "m1",
    term: "s1",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/122494286",
    checked: "2026-08-14",
    chapters: [
      { part: "Ⅰ. 소인수분해", title: "1. 소인수분해", unitId: "m1-s1-01" },
      { part: "Ⅰ. 소인수분해", title: "2. 최대공약수와 최소공배수", unitId: null },
      { part: "Ⅱ. 정수와 유리수", title: "1. 정수와 유리수", unitId: "m1-s1-02" },
      { part: "Ⅱ. 정수와 유리수", title: "2. 정수와 유리수의 계산", unitId: null },
      { part: "Ⅲ. 문자와 식", title: "1. 문자의 사용과 식의 계산", unitId: "m1-s1-03" },
      { part: "Ⅲ. 문자와 식", title: "2. 일차방정식의 풀이", unitId: "m1-s1-04" },
      { part: "Ⅲ. 문자와 식", title: "3. 일차방정식의 활용", unitId: null },
      { part: "Ⅳ. 좌표평면과 그래프", title: "1. 좌표와 그래프", unitId: "m1-s1-05" },
      { part: "Ⅳ. 좌표평면과 그래프", title: "2. 정비례와 반비례", unitId: null },
    ],
  },
  {
    bookId: "rpm-mid",
    grade: "m1",
    term: "s2",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/125105657",
    checked: "2026-08-14",
    chapters: [
      { part: "I. 기본 도형", title: "1. 기본 도형", unitId: "m1-s2-01" },
      { part: "I. 기본 도형", title: "2. 위치 관계", unitId: null },
      { part: "I. 기본 도형", title: "3. 작도와 합동", unitId: "m1-s2-02" },
      { part: "II. 평면도형", title: "1. 다각형", unitId: "m1-s2-03" },
      { part: "II. 평면도형", title: "2. 원과 부채꼴", unitId: null },
      { part: "III. 입체도형", title: "1. 다면체와 회전체", unitId: "m1-s2-04" },
      { part: "III. 입체도형", title: "2. 입체도형의 겉넓이와 부피", unitId: null },
      { part: "IV. 통계", title: "1. 대푯값", unitId: null },
      { part: "IV. 통계", title: "2. 도수분포표와 상대도수", unitId: null },
    ],
  },
  {
    bookId: "rpm-mid",
    grade: "m2",
    term: "s1",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/128928465",
    checked: "2026-08-14",
    chapters: [
      { part: "Ⅰ. 유리수와 순환소수", title: "1. 유리수와 순환소수", unitId: "m2-s1-01" },
      { part: "Ⅱ. 식의 계산", title: "1. 단항식의 계산", unitId: "m2-s1-02" },
      { part: "Ⅱ. 식의 계산", title: "2. 다항식의 계산", unitId: null },
      { part: "Ⅲ. 일차부등식", title: "1. 일차부등식", unitId: "m2-s1-03" },
      { part: "Ⅲ. 일차부등식", title: "2. 일차부등식의 활용", unitId: null },
      { part: "Ⅳ. 연립일차방정식", title: "1. 연립일차방정식", unitId: "m2-s1-04" },
      { part: "Ⅳ. 연립일차방정식", title: "2. 연립일차방정식의 활용", unitId: null },
      { part: "Ⅴ. 일차함수", title: "1. 일차함수와 그 그래프", unitId: null },
      { part: "Ⅴ. 일차함수", title: "2. 일차함수와 일차방정식의 관계", unitId: "m2-s1-06" },
    ],
  },
  {
    bookId: "rpm-mid",
    grade: "m2",
    term: "s2",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/142333494",
    checked: "2026-08-14",
    chapters: [
      { part: "Ⅰ. 삼각형의 성질", title: "1. 삼각형의 성질", unitId: "m2-s2-01" },
      { part: "Ⅰ. 삼각형의 성질", title: "2. 삼각형의 외심과 내심", unitId: null },
      { part: "Ⅱ. 사각형의 성질", title: "1. 평행사변형", unitId: "m2-s2-02" },
      { part: "Ⅱ. 사각형의 성질", title: "2. 여러 가지 사각형", unitId: null },
      { part: "Ⅲ. 도형의 닮음과 피타고라스 정리", title: "1. 도형의 닮음", unitId: "m2-s2-03" },
      { part: "Ⅲ. 도형의 닮음과 피타고라스 정리", title: "2. 평행선 사이의 선분의 길이의 비", unitId: null },
      { part: "Ⅲ. 도형의 닮음과 피타고라스 정리", title: "3. 삼각형의 무게중심", unitId: null },
      { part: "Ⅲ. 도형의 닮음과 피타고라스 정리", title: "4. 피타고라스 정리", unitId: "m2-s2-05" },
      { part: "Ⅳ. 확률", title: "1. 경우의 수", unitId: "m2-s2-06" },
      { part: "Ⅳ. 확률", title: "2. 확률", unitId: null },
    ],
  },
  {
    bookId: "rpm-mid",
    grade: "m3",
    term: "s1",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/113812073",
    checked: "2026-08-14",
    chapters: [
      { part: "I. 실수와 그 연산", title: "1. 제곱근과 실수", unitId: "m3-s1-01" },
      { part: "I. 실수와 그 연산", title: "2. 근호를 포함한 식의 계산", unitId: "m3-s1-02" },
      { part: "II. 다항식의 곱셈과 인수분해", title: "1. 다항식의 곱셈", unitId: "m3-s1-03" },
      { part: "II. 다항식의 곱셈과 인수분해", title: "2. 인수분해", unitId: null },
      { part: "III. 이차방정식", title: "1. 이차방정식의 풀이", unitId: "m3-s1-04" },
      { part: "III. 이차방정식", title: "2. 이차방정식의 활용", unitId: null },
      { part: "IV. 이차함수", title: "1. 이차함수와 그 그래프", unitId: "m3-s1-05" },
      { part: "IV. 이차함수", title: "2. 이차함수 y=ax2+bx+c의 그래프", unitId: null },
    ],
  },
  {
    bookId: "rpm-mid",
    grade: "m3",
    term: "s2",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/108737127",
    checked: "2026-08-14",
    chapters: [
      { part: "I. 삼각비", title: "01 삼각비", unitId: "m3-s2-01" },
      { part: "I. 삼각비", title: "02 삼각비의 활용", unitId: null },
      { part: "II. 원의 성질", title: "03 원과 직선", unitId: "m3-s2-02" },
      { part: "II. 원의 성질", title: "04 원주각", unitId: null },
      { part: "III. 통계", title: "05 대푯값과 산포도", unitId: "m3-s2-03" },
      { part: "III. 통계", title: "06 상관관계", unitId: null },
      { part: "III. 통계", title: "실력 UP+", unitId: null },
    ],
  },
  {
    bookId: "rpm-high",
    grade: "h1",
    term: "s1",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/122957065",
    checked: "2026-08-14",
    chapters: [
      { part: "Ⅰ. 다항식", title: "1. 다항식의 연산", unitId: "h1-s1-01" },
      { part: "Ⅰ. 다항식", title: "2. 항등식과 나머지정리", unitId: null },
      { part: "Ⅰ. 다항식", title: "3. 인수분해", unitId: null },
      { part: "Ⅱ. 방정식과 부등식", title: "1. 복소수", unitId: "h1-s1-02" },
      { part: "Ⅱ. 방정식과 부등식", title: "2. 이차방정식", unitId: "h1-s1-03" },
      { part: "Ⅱ. 방정식과 부등식", title: "3. 이차방정식과 이차함수", unitId: null },
      { part: "Ⅱ. 방정식과 부등식", title: "4. 여러 가지 방정식", unitId: "h1-s1-04" },
      { part: "Ⅱ. 방정식과 부등식", title: "5. 여러 가지 부등식", unitId: null },
      { part: "Ⅲ. 경우의 수", title: "1. 경우의 수와 순열", unitId: "h1-s1-05" },
      { part: "Ⅲ. 경우의 수", title: "2. 조합", unitId: null },
      { part: "Ⅳ. 행렬", title: "1. 행렬", unitId: "h1-s1-06" },
    ],
  },
  {
    bookId: "rpm-high",
    grade: "h1",
    term: "s2",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/124587325",
    checked: "2026-08-14",
    chapters: [
      { title: "Ⅰ 도형의 방정식", unitId: "h1-s2-01" },
      { title: "1 평면좌표", unitId: null },
      { title: "2 직선의 방정식", unitId: null },
      { title: "3 원의 방정식", unitId: null },
      { title: "4 도형의 이동", unitId: null },
      { title: "Ⅱ 집합과 명제", unitId: "h1-s2-02" },
      { title: "1 집합의 뜻과 포함 관계", unitId: null },
      { title: "2 집합의 연산", unitId: null },
      { title: "3 명제", unitId: null },
      { title: "Ⅲ 함수", unitId: null },
      { title: "1 함수", unitId: null },
      { title: "2 유리함수", unitId: null },
      { title: "3 무리함수", unitId: null },
    ],
  },
  {
    bookId: "gnw-mid",
    grade: "m1",
    term: "s1",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/121827017",
    checked: "2026-08-14",
    chapters: [
      { part: "Ⅰ. 소인수분해", title: "1. 소인수분해", unitId: "m1-s1-01" },
      { part: "Ⅰ. 소인수분해", title: "2. 최대공약수와 최소공배수", unitId: null },
      { part: "Ⅱ. 정수와 유리수", title: "1. 정수와 유리수", unitId: "m1-s1-02" },
      { part: "Ⅱ. 정수와 유리수", title: "2. 정수와 유리수의 계산", unitId: null },
      { part: "Ⅲ. 문자와 식", title: "1. 문자의 사용과 식의 계산", unitId: "m1-s1-03" },
      { part: "Ⅲ. 문자와 식", title: "2. 일차방정식의 풀이", unitId: "m1-s1-04" },
      { part: "Ⅲ. 문자와 식", title: "3. 일차방정식의 활용", unitId: null },
      { part: "Ⅳ. 좌표평면과 그래프", title: "1. 좌표와 그래프", unitId: "m1-s1-05" },
      { part: "Ⅳ. 좌표평면과 그래프", title: "2. 정비례와 반비례", unitId: null },
    ],
  },
  {
    bookId: "gnw-mid",
    grade: "m1",
    term: "s2",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/124412954",
    checked: "2026-08-14",
    chapters: [
      { part: "I. 기본 도형", title: "1. 기본 도형", unitId: "m1-s2-01" },
      { part: "I. 기본 도형", title: "2. 위치 관계", unitId: null },
      { part: "I. 기본 도형", title: "3. 작도와 합동", unitId: "m1-s2-02" },
      { part: "II. 평면도형", title: "1. 다각형", unitId: "m1-s2-03" },
      { part: "II. 평면도형", title: "2. 원과 부채꼴", unitId: null },
      { part: "III. 입체도형", title: "1. 다면체와 회전체", unitId: "m1-s2-04" },
      { part: "III. 입체도형", title: "2. 입체도형의 겉넓이와 부피", unitId: null },
      { part: "IV. 통계", title: "1. 대푯값", unitId: null },
      { part: "IV. 통계", title: "2. 도수분포표와 상대도수", unitId: null },
    ],
  },
  {
    bookId: "gnw-mid",
    grade: "m2",
    term: "s1",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/126540504",
    checked: "2026-08-14",
    chapters: [
      { part: "Ⅰ. 유리수와 순환소수", title: "1. 유리수와 순환소수", unitId: "m2-s1-01" },
      { part: "Ⅱ. 식의 계산", title: "1. 단항식의 계산", unitId: "m2-s1-02" },
      { part: "Ⅱ. 식의 계산", title: "2. 다항식의 계산", unitId: null },
      { part: "Ⅲ. 일차부등식", title: "1. 일차부등식", unitId: "m2-s1-03" },
      { part: "Ⅲ. 일차부등식", title: "2. 일차부등식의 활용", unitId: null },
      { part: "Ⅳ. 연립일차방정식", title: "1. 연립일차방정식", unitId: "m2-s1-04" },
      { part: "Ⅳ. 연립일차방정식", title: "2. 연립일차방정식의 활용", unitId: null },
      { part: "Ⅴ. 일차함수", title: "1. 일차함수와 그 그래프", unitId: null },
      { part: "Ⅴ. 일차함수", title: "2. 일차함수와 일차방정식의 관계", unitId: "m2-s1-06" },
    ],
  },
  {
    bookId: "gnw-mid",
    grade: "m2",
    term: "s2",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/138748147",
    checked: "2026-08-14",
    chapters: [
      { part: "Ⅰ. 삼각형의 성질", title: "1. 이등변삼각형", unitId: "m2-s2-01" },
      { part: "Ⅰ. 삼각형의 성질", title: "2. 삼각형의 외심과 내심", unitId: null },
      { part: "Ⅱ. 사각형의 성질", title: "1. 평행사변형", unitId: "m2-s2-02" },
      { part: "Ⅱ. 사각형의 성질", title: "2. 여러 가지 사각형", unitId: null },
      { part: "Ⅲ. 도형의 닮음과 피타고라스 정리", title: "1. 도형의 닮음", unitId: "m2-s2-03" },
      { part: "Ⅲ. 도형의 닮음과 피타고라스 정리", title: "2. 평행선과 선분의 길이의 비", unitId: null },
      { part: "Ⅲ. 도형의 닮음과 피타고라스 정리", title: "3. 삼각형의 무게중심", unitId: null },
      { part: "Ⅲ. 도형의 닮음과 피타고라스 정리", title: "4. 피타고라스 정리", unitId: "m2-s2-05" },
      { part: "Ⅳ. 연립일차방정식", title: "1. 경우의 수", unitId: "m2-s2-06" },
      { part: "Ⅳ. 연립일차방정식", title: "2. 확률", unitId: null },
    ],
  },
  {
    bookId: "gnw-mid",
    grade: "m3",
    term: "s1",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/113811696",
    checked: "2026-08-14",
    chapters: [
      { part: "I. 실수와 그 연산", title: "1. 제곱근과 실수", unitId: "m3-s1-01" },
      { part: "I. 실수와 그 연산", title: "2. 근호를 포함한 식의 계산", unitId: "m3-s1-02" },
      { part: "II. 다항식의 곱셈과 인수분해", title: "1. 다항식의 곱셈", unitId: "m3-s1-03" },
      { part: "II. 다항식의 곱셈과 인수분해", title: "2. 인수분해", unitId: null },
      { part: "III. 이차방정식", title: "1. 이차방정식의 풀이", unitId: "m3-s1-04" },
      { part: "III. 이차방정식", title: "2. 이차방정식의 활용", unitId: null },
      { part: "IV. 이차함수", title: "1. 이차함수와 그 그래프", unitId: "m3-s1-05" },
      { part: "IV. 이차함수", title: "2. 이차함수 y=ax2+bx+c의 그래프", unitId: null },
    ],
  },
  {
    bookId: "gnw-mid",
    grade: "m3",
    term: "s2",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/108737115",
    checked: "2026-08-14",
    chapters: [
      { part: "I. 삼각비", title: "1. 삼각비", unitId: "m3-s2-01" },
      { part: "I. 삼각비", title: "2. 삼각비의 활용", unitId: null },
      { part: "II. 원의 성질", title: "1. 원과 직선", unitId: "m3-s2-02" },
      { part: "II. 원의 성질", title: "2. 원주각", unitId: null },
      { part: "III. 통계", title: "1. 대푯값과 산포도", unitId: "m3-s2-03" },
      { part: "III. 통계", title: "2. 상관관계", unitId: null },
    ],
  },
  {
    bookId: "gnw-high",
    grade: "h1",
    term: "s2",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/123759748",
    checked: "2026-08-14",
    chapters: [
      { title: "Ⅰ 도형의 방정식", unitId: "h1-s2-01" },
      { title: "1 평면좌표", unitId: null },
      { title: "2 직선의 방정식", unitId: null },
      { title: "3 원의 방정식", unitId: null },
      { title: "4 도형의 이동", unitId: null },
      { title: "Ⅱ 집합과 명제", unitId: "h1-s2-02" },
      { title: "1 집합의 뜻과 포함 관계", unitId: null },
      { title: "2 집합의 연산", unitId: null },
      { title: "3 명제", unitId: null },
      { title: "Ⅲ 함수", unitId: null },
      { title: "1 함수", unitId: null },
      { title: "2 유리함수", unitId: null },
      { title: "3 무리함수", unitId: null },
    ],
  },
  {
    bookId: "didim-basic",
    grade: "e3",
    term: "s1",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/152353824",
    checked: "2026-08-14",
    chapters: [
      { title: "1. 덧셈과 뺄셈", unitId: "e3-s1-01" },
      { title: "2. 평면도형", unitId: "e3-s1-02" },
      { title: "3. 나눗셈", unitId: "e3-s1-03" },
      { title: "4. 곱셈", unitId: "e3-s1-04" },
      { title: "5. 길이와 시간", unitId: "e3-s1-05" },
      { title: "6. 분수와 소수", unitId: "e3-s1-06" },
    ],
  },
  {
    bookId: "didim-basic",
    grade: "e3",
    term: "s2",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/174321229",
    checked: "2026-08-14",
    chapters: [
      { title: "1. 곱셈", unitId: "e3-s2-01" },
      { title: "2. 나눗셈", unitId: "e3-s2-02" },
      { title: "3. 원", unitId: "e3-s2-03" },
      { title: "4. 분수", unitId: "e3-s2-04" },
      { title: "5. 들이와 무게", unitId: "e3-s2-05" },
      { title: "6. 자료의 정리", unitId: null },
    ],
  },
  {
    bookId: "didim-basic",
    grade: "e4",
    term: "s1",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/152353932",
    checked: "2026-08-14",
    chapters: [
      { title: "1. 큰 수", unitId: "e4-s1-01" },
      { title: "2. 각도", unitId: "e4-s1-02" },
      { title: "3. 곱셈과 나눗셈", unitId: "e4-s1-03" },
      { title: "4. 평면도형의 이동", unitId: "e4-s1-04" },
      { title: "5. 막대그래프", unitId: "e4-s1-05" },
      { title: "6. 규칙 찾기", unitId: "e4-s1-06" },
    ],
  },
  {
    bookId: "didim-basic",
    grade: "e4",
    term: "s2",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/174321338",
    checked: "2026-08-14",
    chapters: [
      { title: "1. 분수의 덧셈과 뺄셈", unitId: "e4-s2-01" },
      { title: "2. 삼각형", unitId: "e4-s2-02" },
      { title: "3. 소수의 덧셈과 뺄셈", unitId: "e4-s2-03" },
      { title: "4. 사각형", unitId: "e4-s2-04" },
      { title: "5. 꺾은선 그래프", unitId: "e4-s2-05" },
      { title: "6. 다각형", unitId: "e4-s2-06" },
    ],
  },
  {
    bookId: "didim-basic",
    grade: "e5",
    term: "s1",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/152354045",
    checked: "2026-08-14",
    chapters: [
      { title: "1. 자연수의 혼합 계산", unitId: "e5-s1-01" },
      { title: "2. 약수와 배수", unitId: "e5-s1-02" },
      { title: "3. 대응 관계", unitId: "e5-s1-03" },
      { title: "4. 약분과 통분", unitId: "e5-s1-04" },
      { title: "5. 분수의 덧셈과 뺄셈", unitId: "e5-s1-05" },
      { title: "6. 다각형의 둘레와 넓이", unitId: "e5-s1-06" },
    ],
  },
  {
    bookId: "didim-basic",
    grade: "e5",
    term: "s2",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/177742572",
    checked: "2026-08-14",
    chapters: [
      { title: "1. 수의 범위와 어림하기", unitId: "e5-s2-01" },
      { title: "2. 분수의 곱셈", unitId: "e5-s2-02" },
      { title: "3. 합동과 대칭", unitId: "e5-s2-03" },
      { title: "4. 소수의 곱셈", unitId: "e5-s2-04" },
      { title: "5. 직육면체와 정육면체", unitId: "e5-s2-05" },
      { title: "6. 평균과 가능성", unitId: "e5-s2-06" },
    ],
  },
  {
    bookId: "didim-basic",
    grade: "e6",
    term: "s1",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/152354172",
    checked: "2026-08-14",
    chapters: [
      { title: "1. 분수의 나눗셈", unitId: "e6-s1-01" },
      { title: "2. 각기둥과 각뿔", unitId: "e6-s1-02" },
      { title: "3. 소수의 나눗셈", unitId: "e6-s1-03" },
      { title: "4. 비와 비율", unitId: "e6-s1-04" },
      { title: "5. 여러 가지 그래프", unitId: "e6-s1-05" },
      { title: "6. 직육면체의 겉넓이와 부피", unitId: "e6-s1-06" },
    ],
  },
  {
    bookId: "didim-basic",
    grade: "e6",
    term: "s2",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/177743280",
    checked: "2026-08-14",
    chapters: [
      { title: "1. 분수의 나눗셈", unitId: "e6-s2-01" },
      { title: "2. 소수의 나눗셈", unitId: "e6-s2-02" },
      { title: "3. 공간과 입체", unitId: "e6-s2-03" },
      { title: "4. 비례식과 비례배분", unitId: "e6-s2-04" },
      { title: "5. 원의 둘레와 넓이", unitId: "e6-s2-05" },
      { title: "6. 원기둥, 원쁠, 구", unitId: null },
    ],
  },
  {
    bookId: "choisangwi",
    grade: "e3",
    term: "s1",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/134872703",
    checked: "2026-08-14",
    chapters: [
      { title: "1. 덧셈과 뺄셈", unitId: "e3-s1-01" },
      { title: "2. 평면도형", unitId: "e3-s1-02" },
      { title: "3. 나눗셈", unitId: "e3-s1-03" },
      { title: "4. 곱셈", unitId: "e3-s1-04" },
      { title: "5. 길이와 시간", unitId: "e3-s1-05" },
      { title: "6. 분수와 소수", unitId: "e3-s1-06" },
    ],
  },
  {
    bookId: "choisangwi",
    grade: "e3",
    term: "s2",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/144444847",
    checked: "2026-08-14",
    chapters: [
      { title: "1. 곱셈", unitId: "e3-s2-01" },
      { title: "2. 나눗셈", unitId: "e3-s2-02" },
      { title: "3. 원", unitId: "e3-s2-03" },
      { title: "4. 분수", unitId: "e3-s2-04" },
      { title: "5. 들이와 무게", unitId: "e3-s2-05" },
      { title: "6. 자료의 정리", unitId: null },
    ],
  },
  {
    bookId: "choisangwi",
    grade: "e4",
    term: "s1",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/134872736",
    checked: "2026-08-14",
    chapters: [
      { title: "1. 큰 수", unitId: "e4-s1-01" },
      { title: "2. 각도", unitId: "e4-s1-02" },
      { title: "3. 곱셈과 나눗셈", unitId: "e4-s1-03" },
      { title: "4. 평면도형의 이동", unitId: "e4-s1-04" },
      { title: "5. 막대그래프", unitId: "e4-s1-05" },
      { title: "6. 규칙 찾기", unitId: "e4-s1-06" },
    ],
  },
  {
    bookId: "choisangwi",
    grade: "e4",
    term: "s2",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/144444920",
    checked: "2026-08-14",
    chapters: [
      { title: "1. 분수의 덧셈과 뺄셈", unitId: "e4-s2-01" },
      { title: "2. 삼각형", unitId: "e4-s2-02" },
      { title: "3. 소수의 덧셈과 뺄셈", unitId: "e4-s2-03" },
      { title: "4. 사각형", unitId: "e4-s2-04" },
      { title: "5. 꺾은선 그래프", unitId: "e4-s2-05" },
      { title: "6. 다각형", unitId: "e4-s2-06" },
    ],
  },
  {
    bookId: "choisangwi",
    grade: "e5",
    term: "s1",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/154821859",
    checked: "2026-08-14",
    chapters: [
      { title: "1. 자연수의 혼합 계산", unitId: "e5-s1-01" },
      { title: "2. 약수와 배수", unitId: "e5-s1-02" },
      { title: "3. 대응 관계", unitId: "e5-s1-03" },
      { title: "4. 약분과 통분", unitId: "e5-s1-04" },
      { title: "5. 분수의 덧셈과 뺄셈", unitId: "e5-s1-05" },
      { title: "6. 다각형의 둘레와 넓이", unitId: "e5-s1-06" },
    ],
  },
  {
    bookId: "choisangwi",
    grade: "e5",
    term: "s2",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/182708065",
    checked: "2026-08-14",
    chapters: [
      { title: "1. 수의 범위와 어림하기", unitId: "e5-s2-01" },
      { title: "2. 분수의 곱셈", unitId: "e5-s2-02" },
      { title: "3. 합동과 대칭", unitId: "e5-s2-03" },
      { title: "4. 소수의 곱셈", unitId: "e5-s2-04" },
      { title: "5. 직육면체와 정육면체", unitId: "e5-s2-05" },
      { title: "6. 평균과 가능성", unitId: "e5-s2-06" },
    ],
  },
  {
    bookId: "checkcheck",
    grade: "m1",
    term: "s1",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/126540298",
    checked: "2026-08-14",
    chapters: [
      { title: "1 소인수분해", unitId: "m1-s1-01" },
      { title: "2 정수와 유리수", unitId: "m1-s1-02" },
      { title: "3 문자의 사용과 식", unitId: "m1-s1-03" },
      { title: "4 일차방정식", unitId: "m1-s1-04" },
      { title: "5 좌표평면과 그래프", unitId: "m1-s1-05" },
    ],
  },
  {
    bookId: "checkcheck",
    grade: "m1",
    term: "s2",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/141399589",
    checked: "2026-08-14",
    chapters: [
      { title: "1 기본도형", unitId: "m1-s2-01" },
      { title: "2 작도와 합동", unitId: "m1-s2-02" },
      { title: "3 평면도형", unitId: "m1-s2-03" },
      { title: "4 입체도형", unitId: "m1-s2-04" },
      { title: "5 자료의 정리와 해석", unitId: "m1-s2-05" },
    ],
  },
  {
    bookId: "checkcheck",
    grade: "m2",
    term: "s1",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/148031883",
    checked: "2026-08-14",
    chapters: [
      { title: "1 유리수와 순환소수", unitId: "m2-s1-01" },
      { title: "2 식의 계산", unitId: "m2-s1-02" },
      { title: "3 일차부등식", unitId: "m2-s1-03" },
      { title: "4 연립일차방정식", unitId: "m2-s1-04" },
      { title: "5 일차함수와 그래프(1)", unitId: "m2-s1-05" },
      { title: "6 일차함수와 그래프(2)", unitId: null },
      { title: "7 일차함수와 일차방정식의 관계", unitId: "m2-s1-06" },
    ],
  },
  {
    bookId: "checkcheck",
    grade: "m2",
    term: "s2",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/161440419",
    checked: "2026-08-14",
    chapters: [
      { title: "1 삼각형의 성질", unitId: "m2-s2-01" },
      { title: "2 사각형의 성질", unitId: "m2-s2-02" },
      { title: "3 도형의 닮음", unitId: "m2-s2-03" },
      { title: "4 닮음의 응용", unitId: null },
      { title: "5 피타고라스 정리", unitId: "m2-s2-05" },
      { title: "6 경우의 수", unitId: "m2-s2-06" },
      { title: "7 확률", unitId: null },
    ],
  },
  {
    bookId: "checkcheck",
    grade: "m3",
    term: "s1",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/133338333",
    checked: "2026-08-14",
    chapters: [
      { title: "1 제곱근과 무리수", unitId: null },
      { title: "2 근호를 포함한 식의 계산", unitId: "m3-s1-02" },
      { title: "3 다항식의 곱셈", unitId: "m3-s1-03" },
      { title: "4 인수분해", unitId: null },
      { title: "5 이차방정식", unitId: "m3-s1-04" },
      { title: "6 이차함수", unitId: "m3-s1-05" },
      { title: "7 이차함수의 활용", unitId: null },
    ],
  },
  {
    bookId: "ilpum",
    grade: "m1",
    term: "s1",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/145056498",
    checked: "2026-08-14",
    chapters: [
      { part: "Ⅰ. 수와 연산", title: "01. 소인수분해", unitId: "m1-s1-01" },
      { part: "Ⅰ. 수와 연산", title: "02. 정수와 유리수", unitId: "m1-s1-02" },
      { part: "Ⅰ. 수와 연산", title: "03. 유리수의 계산", unitId: null },
      { part: "Ⅱ. 방정식", title: "04. 문자의 사용과 식", unitId: "m1-s1-03" },
      { part: "Ⅱ. 방정식", title: "05. 일차방정식", unitId: "m1-s1-04" },
      { part: "Ⅲ. 그래프와 비례", title: "06. 좌표평면과 그래프", unitId: "m1-s1-05" },
      { part: "Ⅲ. 그래프와 비례", title: "07. 정비례와 반비례", unitId: null },
    ],
  },
  {
    bookId: "ilpum",
    grade: "m1",
    term: "s2",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/140472999",
    checked: "2026-08-14",
    chapters: [
      { part: "Ⅰ. 기본 도형", title: "01. 기본 도형", unitId: "m1-s2-01" },
      { part: "Ⅰ. 기본 도형", title: "02. 위치 관계", unitId: null },
      { part: "Ⅰ. 기본 도형", title: "03. 작도와 합동", unitId: "m1-s2-02" },
      { part: "Ⅱ. 평면도형", title: "04. 다각형", unitId: "m1-s2-03" },
      { part: "Ⅱ. 평면도형", title: "05. 원과 부채꼴", unitId: null },
      { part: "Ⅲ. 입체도형", title: "06. 다면체와 회전체", unitId: "m1-s2-04" },
      { part: "Ⅲ. 입체도형", title: "07. 입체도형의 겉넓이와 부피", unitId: null },
      { part: "Ⅳ. 통계", title: "08 도수분포표", unitId: null },
      { part: "Ⅳ. 통계", title: "09 상대도수", unitId: null },
    ],
  },
  {
    bookId: "ilpum",
    grade: "m2",
    term: "s1",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/143648126",
    checked: "2026-08-14",
    chapters: [
      { part: "Ⅰ. 수와 식", title: "01. 유리수와 소수", unitId: null },
      { part: "Ⅰ. 수와 식", title: "02. 단항식의 계산", unitId: "m2-s1-02" },
      { part: "Ⅰ. 수와 식", title: "03. 다항식의 계산", unitId: null },
      { part: "Ⅱ. 부등식", title: "04. 일차부등식", unitId: "m2-s1-03" },
      { part: "Ⅱ. 부등식", title: "05. 일차부등식의 활용", unitId: null },
      { part: "Ⅲ. 방정식", title: "06. 연립일차방정식의 풀이", unitId: "m2-s1-04" },
      { part: "Ⅲ. 방정식", title: "07. 연립일차방정식의 활용", unitId: null },
      { part: "Ⅳ. 함수", title: "08 일차함수와 그래프", unitId: "m2-s1-05" },
      { part: "Ⅳ. 함수", title: "09 일차함수와 일차방정식의 관계", unitId: "m2-s1-06" },
    ],
  },
  {
    bookId: "ilpum",
    grade: "m2",
    term: "s2",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/153641657",
    checked: "2026-08-14",
    chapters: [
      { part: "Ⅰ. 도형의 성질", title: "01. 삼각형의 성질", unitId: "m2-s2-01" },
      { part: "Ⅰ. 도형의 성질", title: "02. 평행사변형의 성질", unitId: null },
      { part: "Ⅰ. 도형의 성질", title: "03. 여러 가지 사각형의 성질", unitId: "m2-s2-02" },
      { part: "Ⅱ. 도형의 닮음", title: "04. 도형의 닮음", unitId: "m2-s2-03" },
      { part: "Ⅱ. 도형의 닮음", title: "05. 평행선 사이의 선분의 길이의 비", unitId: null },
      { part: "Ⅱ. 도형의 닮음", title: "06. 닮음의 활용", unitId: null },
      { part: "Ⅲ. 피타고라스 정리", title: "07. 피타고라스 정리", unitId: "m2-s2-05" },
      { part: "Ⅳ. 확률", title: "08. 경우의 수", unitId: "m2-s2-06" },
      { part: "Ⅳ. 확률", title: "09. 확률", unitId: null },
    ],
  },
  {
    bookId: "ilpum",
    grade: "m3",
    term: "s1",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/125028562",
    checked: "2026-08-14",
    chapters: [
      { part: "Ⅰ. 제곱근과 실수", title: "1. 제곱근과 실수", unitId: "m3-s1-01" },
      { part: "Ⅰ. 제곱근과 실수", title: "2. 근호를 포함한 식의 곱셈과 나눗셈", unitId: null },
      { part: "Ⅰ. 제곱근과 실수", title: "3. 근호를 포함한 식의 덧셈과 뺄셈", unitId: null },
      { part: "Ⅱ. 다항식의 곱셈과 인수분해", title: "1. 다항식의 곱셈", unitId: "m3-s1-03" },
      { part: "Ⅱ. 다항식의 곱셈과 인수분해", title: "2. 다항식의 인수분해", unitId: null },
      { part: "Ⅲ. 이차방정식", title: "1. 이차방정식의 풀이", unitId: "m3-s1-04" },
      { part: "Ⅲ. 이차방정식", title: "2. 이차방정식의 활용", unitId: null },
      { part: "Ⅳ. 이차함수", title: "1. 이차함수의 그래프", unitId: "m3-s1-05" },
    ],
  },
  {
    bookId: "ilpum",
    grade: "m3",
    term: "s2",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/123387613",
    checked: "2026-08-14",
    chapters: [
      { part: "Ⅰ. 삼각비", title: "1. 삼각비", unitId: "m3-s2-01" },
      { part: "Ⅰ. 삼각비", title: "2. 삼각비의 활용", unitId: null },
      { part: "Ⅱ. 원의 성질", title: "1. 원과 직선", unitId: "m3-s2-02" },
      { part: "Ⅱ. 원의 성질", title: "2. 원주각", unitId: null },
      { part: "Ⅲ. 통계", title: "1. 대푯값과 산포도", unitId: "m3-s2-03" },
      { part: "Ⅲ. 통계", title: "2. 상관관계", unitId: null },
    ],
  },
  {
    bookId: "baekbal",
    grade: "m1",
    term: "s1",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/135146798",
    checked: "2026-08-14",
    chapters: [
      { part: "Ⅰ. 수와 연산", title: "1. 소인수분해", unitId: "m1-s1-01" },
      { part: "Ⅰ. 수와 연산", title: "2. 정수와 유리수", unitId: "m1-s1-02" },
      { part: "Ⅱ. 문자와 식", title: "3. 문자의 사용과 식", unitId: "m1-s1-03" },
      { part: "Ⅱ. 문자와 식", title: "4. 일차방정식", unitId: "m1-s1-04" },
      { part: "Ⅲ. 좌표평면과 그래프", title: "5. 좌표평면과 그래프", unitId: "m1-s1-05" },
    ],
  },
  {
    bookId: "baekbal",
    grade: "m1",
    term: "s2",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/135146918",
    checked: "2026-08-14",
    chapters: [
      { part: "Ⅰ. 기본 도형", title: "1. 기본 도형", unitId: "m1-s2-01" },
      { part: "Ⅰ. 기본 도형", title: "2. 작도와 합동", unitId: "m1-s2-02" },
      { part: "Ⅱ. 평면도형", title: "3. 다각형", unitId: "m1-s2-03" },
      { part: "Ⅱ. 평면도형", title: "4. 원과 부채꼴", unitId: null },
      { part: "Ⅲ. 입체도형", title: "5. 다면체와 회전체", unitId: "m1-s2-04" },
      { part: "Ⅲ. 입체도형", title: "6. 입체도형의 겉넓이와 부피", unitId: null },
      { part: "Ⅳ. 통계", title: "7. 자료의 정리와 해석", unitId: "m1-s2-05" },
    ],
  },
  {
    bookId: "baekbal",
    grade: "m2",
    term: "s1",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/159178413",
    checked: "2026-08-14",
    chapters: [
      { part: "Ⅰ. 수와 식의 계산", title: "1. 유리수와 순환소수", unitId: "m2-s1-01" },
      { part: "Ⅰ. 수와 식의 계산", title: "2. 식의 계산", unitId: "m2-s1-02" },
      { part: "Ⅱ. 부등식과 연립방정식", title: "3. 일차부등식", unitId: "m2-s1-03" },
      { part: "Ⅱ. 부등식과 연립방정식", title: "4. 연립일차방정식", unitId: "m2-s1-04" },
      { part: "Ⅲ. 일차함수", title: "5. 일차함수와 그 그래프", unitId: null },
      { part: "Ⅲ. 일차함수", title: "6. 일차함수와 일차방정식의 관계", unitId: "m2-s1-06" },
    ],
  },
  {
    bookId: "baekbal",
    grade: "m2",
    term: "s2",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/169227563",
    checked: "2026-08-14",
    chapters: [
      { part: "Ⅰ. 도형의 성질", title: "1. 삼각형의 성질", unitId: "m2-s2-01" },
      { part: "Ⅰ. 도형의 성질", title: "2. 사각형의 성질", unitId: "m2-s2-02" },
      { part: "Ⅱ. 도형의 닮음과 피타고라스 정리", title: "3. 도형의 닮음", unitId: "m2-s2-03" },
      { part: "Ⅱ. 도형의 닮음과 피타고라스 정리", title: "4. 평행선 사이의 선분의 길이의 비", unitId: null },
      { part: "Ⅱ. 도형의 닮음과 피타고라스 정리", title: "5. 피타고라스 정리", unitId: "m2-s2-05" },
      { part: "Ⅲ. 확률", title: "6. 경우의 수", unitId: "m2-s2-06" },
      { part: "Ⅲ. 확률", title: "7. 확률", unitId: null },
    ],
  },
  {
    bookId: "baekbal",
    grade: "m3",
    term: "s1",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/135146880",
    checked: "2026-08-14",
    chapters: [
      { part: "Ⅰ. 실수와 그 계산", title: "1. 제곱근과 실수", unitId: "m3-s1-01" },
      { part: "Ⅰ. 실수와 그 계산", title: "2. 근호를 포함한 식의 계산", unitId: "m3-s1-02" },
      { part: "Ⅱ. 다항식의 곱셈과 인수분해", title: "3. 다항식의 곱셈", unitId: "m3-s1-03" },
      { part: "Ⅱ. 다항식의 곱셈과 인수분해", title: "4. 인수분해", unitId: null },
      { part: "Ⅲ. 이차방정식", title: "5. 이차방정식과 그 풀이", unitId: "m3-s1-04" },
      { part: "Ⅲ. 이차방정식", title: "6. 이차방정식의 활용", unitId: null },
      { part: "Ⅳ. 이차함수", title: "7. 이차함수의 그래프 (1)", unitId: "m3-s1-05" },
      { part: "Ⅳ. 이차함수", title: "8. 이차함수의 그래프 (2)", unitId: null },
    ],
  },
  {
    bookId: "baekbal",
    grade: "m3",
    term: "s2",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/135146974",
    checked: "2026-08-14",
    chapters: [
      { part: "Ⅰ. 삼각비", title: "1. 삼각비", unitId: "m3-s2-01" },
      { part: "Ⅰ. 삼각비", title: "2. 삼각비의 활용", unitId: null },
      { part: "Ⅱ. 원의 성질", title: "3. 원과 직선", unitId: "m3-s2-02" },
      { part: "Ⅱ. 원의 성질", title: "4. 원주각", unitId: null },
      { part: "Ⅲ. 통계", title: "5. 대푯값과 산포도", unitId: "m3-s2-03" },
      { part: "Ⅲ. 통계", title: "6. 상관관계", unitId: null },
    ],
  },
  {
    bookId: "mapl",
    grade: "h1",
    term: "s1",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/133710255",
    checked: "2026-08-14",
    chapters: [
      { part: "I. 다항식", title: "01 다항식의 연산", unitId: "h1-s1-01" },
      { part: "I. 다항식", title: "02 항등식과 나머지정리", unitId: null },
      { part: "I. 다항식", title: "03 인수분해", unitId: null },
      { part: "II. 방정식과 부등식", title: "01 복소수", unitId: "h1-s1-02" },
      { part: "II. 방정식과 부등식", title: "02 이차방정식", unitId: "h1-s1-03" },
      { part: "II. 방정식과 부등식", title: "03 이차방정식과 이차함수", unitId: null },
      { part: "II. 방정식과 부등식", title: "04 여러 가지 방정식", unitId: "h1-s1-04" },
      { part: "II. 방정식과 부등식", title: "05 일차부등식", unitId: null },
      { part: "II. 방정식과 부등식", title: "06 이차부등식", unitId: null },
      { part: "III. 경우의 수", title: "01 경우의 수", unitId: "h1-s1-05" },
      { part: "III. 경우의 수", title: "02 순열", unitId: null },
      { part: "III. 경우의 수", title: "03 조합", unitId: null },
      { part: "IV. 행렬", title: "01 행렬", unitId: "h1-s1-06" },
    ],
  },
  {
    bookId: "mapl",
    grade: "h1",
    term: "s2",
    edition: "2026년판",
    source: "https://www.yes24.com/product/goods/137429833",
    checked: "2026-08-14",
    chapters: [
      { part: "I. 도형의 방정식", title: "01 평면좌표", unitId: "h1-s2-01" },
      { part: "I. 도형의 방정식", title: "02 직선의 방정식", unitId: null },
      { part: "I. 도형의 방정식", title: "03 원의 방정식", unitId: null },
      { part: "I. 도형의 방정식", title: "04 도형의 이동", unitId: null },
      { part: "II. 집합과 명제", title: "01 집합", unitId: "h1-s2-02" },
      { part: "II. 집합과 명제", title: "02 명제", unitId: null },
      { part: "II. 집합과 명제", title: "03 절대부등식", unitId: null },
      { part: "III. 함수와 그래프", title: "01 함수", unitId: "h1-s2-03" },
      { part: "III. 함수와 그래프", title: "02 합성함수와 역함수", unitId: null },
      { part: "III. 함수와 그래프", title: "03 유리함수", unitId: null },
      { part: "III. 함수와 그래프", title: "04 무리함수", unitId: null },
    ],
  },
];
